### ISSUE TITLE
Failed to install addon

### ISSUE THREAD

**Issue by TheGroundZero** [synesthesiam/hassio-addons#19]
Hi

I'm trying to install the Rhasspy Assistant add-on on Home Assistant.  
The idea would be to use my HA system as base station and install one or more RPi's as sattelites.

Sadly enough, the install fails on me :(

![image](https://user-images.githubusercontent.com/2406013/103537194-e5567000-4e8b-11eb-921f-f94cd69294b1.png)

**Comment by TheGroundZero** [comment]
Weirdly enough, it does appear as installed add-on.

Starting the add-on and checking the logs

```log
[DEBUG:2021-01-04 12:55:24,955] rhasspyserver_hermes: Connecting to localhost:12183 (retries: 0/10)
[ERROR:2021-01-04 12:55:24,987] rhasspyserver_hermes: mqtt connect
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 289, in start
    self.client.connect(self.host, self.port)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
2021-01-04 12:55:25,047 INFO spawned: 'mqtt' with pid 195
1609764925: mosquitto version 1.6.6 starting
1609764925: Using default config.
1609764925: Opening ipv4 listen socket on port 12183.
1609764925: Opening ipv6 listen socket on port 12183.
```

It does seem to run now ... Web UI is reachable at HA:12101

**Comment by synesthesiam** [comment]
Was Rhasspy 2.4 running previously?

**Comment by TheGroundZero** [comment]
This was at the first install of the Rhasspy add-on.

It's running now (and updated to 2.5.9 by now).
