### ISSUE TITLE
Hassio addon install failure

### ISSUE THREAD

**Issue by SamJongenelen** [synesthesiam/hassio-addons#27]
Rhasspy Assistant addon in Home assistant from this repository fails for me.
I've had Rhasppy installed a couple of months ago and it worked. Now supervisor just tells me there is something wrong with the container?

```
21-03-04 16:01:23 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'NoneType' object has no attribute 'is_file'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 100, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 182, in install
    await addon.instance.install(store.version, store.image)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 32, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 491, in _install
    self._build(version)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 500, in _build
    build_env = AddonBuild(self.coresys, self.addon)
  File "/usr/src/supervisor/supervisor/addons/build.py", line 32, in __init__
    super().__init__(
  File "/usr/src/supervisor/supervisor/utils/common.py", line 59, in __init__
    self.read_data()
  File "/usr/src/supervisor/supervisor/utils/common.py", line 72, in read_data
    if self._file.is_file():
AttributeError: 'NoneType' object has no attribute 'is_file'
```

HA Home Assistant 2021.3.0
supervisor-2021.03.3

**Comment by SamJongenelen** [comment]
Turns out I've been able to install after a clean boot. Still having issues with hermes (not starting) though, but thats another issue
