### ISSUE TITLE
Mozilla DeepSpeech doesn't work

### ISSUE THREAD

**Issue by tykarol** [synesthesiam/hassio-addons#30]
Fresh install of the addon and when I select "Mozilla DeepSpeach" in "Speach to Text" I get the errors like below:

```
2021-04-11 20:39:09,560 INFO spawned: 'speech_to_text' with pid 5943
2021-04-11 20:39:10,563 INFO success: speech_to_text entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/rhasspy/rhasspy-asr-deepspeech-hermes/rhasspyasr_deepspeech_hermes/__init__.py", line 13, in <module>
    import rhasspyasr_deepspeech
  File "/usr/lib/rhasspy/rhasspy-asr-deepspeech/rhasspyasr_deepspeech/__init__.py", line 3, in <module>
    from .transcribe import DeepSpeechTranscriber
  File "/usr/lib/rhasspy/rhasspy-asr-deepspeech/rhasspyasr_deepspeech/transcribe.py", line 10, in <module>
    import deepspeech
ModuleNotFoundError: No module named 'deepspeech'
2021-04-11 20:39:11,226 INFO exited: speech_to_text (exit status 1; not expected)
```

When I try to install deepspeach using (in addon docker container):

`pip3 install deepspeech`

a get:

```
Could not find a version that satisfies the requirement deepspeech (from versions: )
No matching distribution found for deepspeech
```

and with verbose flag:

```
Created temporary directory: /tmp/pip-ephem-wheel-cache-290odysy
Created temporary directory: /tmp/pip-req-tracker-xg85ijxr
Created requirements tracker '/tmp/pip-req-tracker-xg85ijxr'
Created temporary directory: /tmp/pip-install-acrjaejb
Collecting deepspeech
  1 location(s) to search for versions of deepspeech:
  * https://pypi.org/simple/deepspeech/
  Getting page https://pypi.org/simple/deepspeech/
  Looking up "https://pypi.org/simple/deepspeech/" in the cache
  Current age based on date: 109
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 0
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/deepspeech/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/deepspeech/
    Skipping link https://files.pythonhosted.org/packages/4f/71/3fbcf9309730496777375a51d441d33ec9c6a036dd0f9da5c09848625801/deepspeech-0.0.2-cp27-cp27m-macosx_10_12_x86_64.whl#sha256=b186405784bb989759a241d2f75e2aa88b4f88dd6377393620e45865cfcc0af8 (from https://pypi.org/simple/deepspeech/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/2a/ce/d021efbe13a50644a23880dfb3bd9f3d7cd35f167fa3d263c7a1d5c499c9/deepspeech-0.0.2-cp27-cp27mu-linux_armv7l.whl#sha256=9386b5fa56b70cf64beb8d4290577b5a43d53696ccb7fd85e4be72260aad9d18 (from https://pypi.org/simple/deepspeech/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/6b/04/b93cac108650c8fb2dad4d381dbc1add8cc1992b27ae247f86b758bcd030/deepspeech-0.0.2-cp27-cp27mu-manylinux1_x86_64.whl#sha256=a73f90242bf173828f5b4e2dc5b7dd0ca34c4668ff7322a84e7c944c35aa11d9 (from https://pypi.org/simple/deepspeech/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/13/04/22c7aba1d8f3528860a3f7da93a8271da660917a16bf04ab3d69806ddbdb/deepspeech-0.0.2-cp34-cp34m-linux_armv7l.whl#sha256=c3caf89faebcb548ddc2e77772fc3747374f973bb40753575c23633f8be3f614 (from https://pypi.org/simple/deepspeech/); it is not compatible with this Python
[...]
    Skipping link https://files.pythonhosted.org/packages/b0/38/b9580dec0dbe38f872bcc8c03f43f0eebfd5129ba661f4b3f1d02aa76e99/deepspeech-0.10.0a3-cp39-cp39-win_amd64.whl#sha256=732909640693ef3b7d27bf28a503868660f647a862a0ea6b0d2d00a7e45cd800 (from https://pypi.org/simple/deepspeech/); it is not compatible with this Python
  Could not find a version that satisfies the requirement deepspeech (from versions: )
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-xg85ijxr'
No matching distribution found for deepspeech
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 338, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 218, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 164, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/_internal/index.py", line 621, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for deepspeech
```

```
# pip3 --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)

# python3.7 --version
Python 3.7.3

# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

# uname -a
Linux 75f2ff60-rhasspy 5.4.83-v8 #1 SMP PREEMPT Thu Apr 1 18:30:43 UTC 2021 aarch64 GNU/Linux
```

**Comment by tykarol** [comment]
Installed missing package with:

```
pip3 install --upgrade setuptools pip
pip3 install https://github.com/mozilla/DeepSpeech/releases/download/v0.9.3/deepspeech-0.9.3-cp37-cp37m-linux_aarch64.whl
```

but still have the same errors in the log file, restart of rassphy also doesn't help, when restart the addon then all be reverted (old version of pip and no deepspeech package).

**Comment by synesthesiam** [comment]
Please try the OpenTTS add-ons instead, as they're more up to date.

**Comment by tykarol** [comment]
But as I checked the OpenTTS not support the Polish language :/

śr., 16 cze 2021, 21:29 użytkownik Michael Hansen ***@***.***>
napisał:

**Comment by synesthesiam** [comment]
I'm sorry! I had "Mozilla TTS" in my head from a different issue.

I will figure out what the problem is. Looks like you're on a 64-bit ARM system with Debian buster.

**Comment by tykarol** [comment]
I have Home Assistant OS on the rpi4-64 (aarch64).

śr., 16 cze 2021, 21:53 użytkownik Michael Hansen ***@***.***>
napisał:

**Comment by synesthesiam** [comment]
They don't seem to have a 64-bit ARM wheel up on PyPI. Try this instead:

```sh
pip install 'https://github.com/mozilla/DeepSpeech/releases/download/v0.9.3/deepspeech-0.9.3-cp37-cp37m-linux_aarch64.whl'
```

**Comment by tykarol** [comment]
I tried this in https://github.com/synesthesiam/hassio-addons/issues/30#issuecomment-817368610 but I do this again using `pip3` (`pip` is not found in the docker `addon_75f2ff60_rhasspy` container).

<details><summary>Full stdout from that command here</summary>
<p>
```
# pip3 install 'https://github.com/mozilla/DeepSpeech/releases/download/v0.9.3/deepspeech-0.9.3-c
p37-cp37m-linux_aarch64.whl'
Collecting deepspeech==0.9.3 from https://github.com/mozilla/DeepSpeech/releases/download/v0.9.3/deepspeech-0.9.3-cp37-cp37m-linux_aarch64.whl
  Downloading https://github.com/mozilla/DeepSpeech/releases/download/v0.9.3/deepspeech-0.9.3-cp37-cp37m-linux_aarch64.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 292kB/s
Collecting numpy>=1.14.5 (from deepspeech==0.9.3)
  Downloading https://files.pythonhosted.org/packages/66/03/818876390c7ff4484d5a05398a618cfdaf0a2b9abb3a7c7ccd59fe181008/numpy-1.21.0.zip (10.3MB)
    100% |████████████████████████████████| 10.3MB 50kB/s
  Installing build dependencies ... done
Building wheels for collected packages: numpy
  Running setup.py bdist_wheel for numpy ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-6n_fzlcg/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-bv_1sgad --python-tag cp37:
  Running from numpy source directory.
  Cythonizing sources
  Processing numpy/random/_bounded_integers.pxd.in
  Processing numpy/random/_philox.pyx
  Processing numpy/random/_pcg64.pyx
  Processing numpy/random/mtrand.pyx
  Processing numpy/random/_bounded_integers.pyx.in
  Processing numpy/random/_sfc64.pyx
  Processing numpy/random/_mt19937.pyx
  Processing numpy/random/_common.pyx
  Processing numpy/random/_generator.pyx
  Processing numpy/random/bit_generator.pyx
  blas_opt_info:
  blas_mkl_info:
  customize UnixCCompiler
    libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  blis_info:
    libraries blis not found in ['/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  openblas_info:
    libraries openblas not found in ['/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  accelerate_info:
    NOT AVAILABLE

  atlas_3_10_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas not found in ['/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  atlas_3_10_blas_info:
    libraries satlas not found in ['/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  atlas_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  atlas_blas_info:
    libraries f77blas,cblas,atlas not found in ['/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  /tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/system_info.py:2026: UserWarning:
      Optimized (vendor) Blas libraries are not found.
      Falls back to netlib Blas library which has worse performance.
      A better performance should be easily gained by switching
      Blas library.
    if self._calc_info(blas):
  blas_info:
    libraries blas not found in ['/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  /tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/system_info.py:2026: UserWarning:
      Blas (http://www.netlib.org/blas/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [blas]) or by setting
      the BLAS environment variable.
    if self._calc_info(blas):
  blas_src_info:
    NOT AVAILABLE

  /tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/system_info.py:2026: UserWarning:
      Blas (http://www.netlib.org/blas/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [blas_src]) or by setting
      the BLAS_SRC environment variable.
    if self._calc_info(blas):
    NOT AVAILABLE

  non-existing path in 'numpy/distutils': 'site.cfg'
  lapack_opt_info:
  lapack_mkl_info:
    libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  openblas_lapack_info:
    libraries openblas not found in ['/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  openblas_clapack_info:
    libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  flame_info:
    libraries flame not found in ['/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
    libraries lapack_atlas not found in /usr/local/lib
    libraries tatlas,tatlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/lib
    libraries tatlas,tatlas not found in /usr/lib
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
    libraries lapack_atlas not found in /usr/local/lib
    libraries satlas,satlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/lib
    libraries satlas,satlas not found in /usr/lib
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
    libraries lapack_atlas not found in /usr/local/lib
    libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/lib
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
    libraries lapack_atlas not found in /usr/local/lib
    libraries f77blas,cblas,atlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/lib
    libraries f77blas,cblas,atlas not found in /usr/lib
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  lapack_info:
    libraries lapack not found in ['/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  /tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/system_info.py:1858: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
  lapack_src_info:
    NOT AVAILABLE

  /tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/system_info.py:1858: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
    NOT AVAILABLE

  numpy_linalg_lapack_lite:
    FOUND:
      language = c
      define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]

  Warning: attempted relative import with no known parent package
  /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building py_modules sources
  creating build
  creating build/src.linux-aarch64-3.7
  creating build/src.linux-aarch64-3.7/numpy
  creating build/src.linux-aarch64-3.7/numpy/distutils
  building library "npymath" sources
  Could not locate executable gfortran
  Could not locate executable f95
  Could not locate executable ifort
  Could not locate executable ifc
  Could not locate executable lf95
  Could not locate executable pgfortran
  Could not locate executable nvfortran
  Could not locate executable f90
  Could not locate executable f77
  Could not locate executable fort
  Could not locate executable efort
  Could not locate executable efc
  Could not locate executable g77
  Could not locate executable g95
  Could not locate executable pathf95
  Could not locate executable nagfor
  Could not locate executable frt
  don't know how to compile Fortran code on platform 'posix'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-6n_fzlcg/numpy/setup.py", line 447, in <module>
      setup_package()
    File "/tmp/pip-install-6n_fzlcg/numpy/setup.py", line 439, in setup_package
      setup(**metadata)
    File "/tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/core.py", line 169, in setup
      return old_setup(**new_attr)
    File "/tmp/pip-build-env-3yl6_f19/lib/python3.7/site-packages/setuptools/__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-3yl6_f19/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/command/build.py", line 61, in run
      old_build.run(self)
    File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/command/build_src.py", line 144, in run
      self.build_sources()
    File "/tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/command/build_src.py", line 155, in build_sources
      self.build_library_sources(*libname_info)
    File "/tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/command/build_src.py", line 288, in build_library_sources
      sources = self.generate_sources(sources, (lib_name, build_info))
    File "/tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/command/build_src.py", line 378, in generate_sources
      source = func(extension, build_dir)
    File "numpy/core/setup.py", line 666, in get_mathlib_info
      raise RuntimeError("Broken toolchain: cannot link a simple C program")
  RuntimeError: Broken toolchain: cannot link a simple C program

  ----------------------------------------
  Failed building wheel for numpy
  Running setup.py clean for numpy
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-6n_fzlcg/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Running from numpy source directory.

  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).


  ----------------------------------------
  Failed cleaning build dir for numpy
Failed to build numpy
Installing collected packages: numpy, deepspeech
  Running setup.py install for numpy ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-6n_fzlcg/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-980d0neu/install-record.txt --single-version-externally-managed --compile:
    Running from numpy source directory.

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install numpy`   (last NumPy release on PyPi)


    Cythonizing sources
    numpy/random/_bounded_integers.pxd.in has not changed
    numpy/random/_philox.pyx has not changed
    numpy/random/_pcg64.pyx has not changed
    Processing numpy/random/_bounded_integers.pyx
    numpy/random/mtrand.pyx has not changed
    numpy/random/_bounded_integers.pyx.in has not changed
    numpy/random/_sfc64.pyx has not changed
    numpy/random/_mt19937.pyx has not changed
    numpy/random/_common.pyx has not changed
    numpy/random/_generator.pyx has not changed
    numpy/random/bit_generator.pyx has not changed
    blas_opt_info:
    blas_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    blis_info:
      libraries blis not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    openblas_info:
      libraries openblas not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    accelerate_info:
      NOT AVAILABLE

    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_3_10_blas_info:
      libraries satlas not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    /tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/system_info.py:2026: UserWarning:
        Optimized (vendor) Blas libraries are not found.
        Falls back to netlib Blas library which has worse performance.
        A better performance should be easily gained by switching
        Blas library.
      if self._calc_info(blas):
    blas_info:
      libraries blas not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    /tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/system_info.py:2026: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      if self._calc_info(blas):
    blas_src_info:
      NOT AVAILABLE

    /tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/system_info.py:2026: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      if self._calc_info(blas):
      NOT AVAILABLE

    non-existing path in 'numpy/distutils': 'site.cfg'
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    openblas_clapack_info:
      libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    flame_info:
      libraries flame not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in /usr/local/lib
      libraries tatlas,tatlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries tatlas,tatlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries lapack_atlas not found in /usr/local/lib
      libraries satlas,satlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries satlas,satlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in /usr/local/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries lapack_atlas not found in /usr/local/lib
      libraries f77blas,cblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries f77blas,cblas,atlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    lapack_info:
      libraries lapack not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    /tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/system_info.py:1858: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    lapack_src_info:
      NOT AVAILABLE

    /tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/system_info.py:1858: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
      NOT AVAILABLE

    numpy_linalg_lapack_lite:
      FOUND:
        language = c
        define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]

    Warning: attempted relative import with no known parent package
    /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building py_modules sources
    building library "npymath" sources
    Could not locate executable gfortran
    Could not locate executable f95
    Could not locate executable ifort
    Could not locate executable ifc
    Could not locate executable lf95
    Could not locate executable pgfortran
    Could not locate executable nvfortran
    Could not locate executable f90
    Could not locate executable f77
    Could not locate executable fort
    Could not locate executable efort
    Could not locate executable efc
    Could not locate executable g77
    Could not locate executable g95
    Could not locate executable pathf95
    Could not locate executable nagfor
    Could not locate executable frt
    don't know how to compile Fortran code on platform 'posix'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6n_fzlcg/numpy/setup.py", line 447, in <module>
        setup_package()
      File "/tmp/pip-install-6n_fzlcg/numpy/setup.py", line 439, in setup_package
        setup(**metadata)
      File "/tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/tmp/pip-build-env-3yl6_f19/lib/python3.7/site-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/command/install.py", line 60, in run
        r = self.setuptools_run()
      File "/tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/command/install.py", line 34, in setuptools_run
        return distutils_install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/command/build.py", line 61, in run
        old_build.run(self)
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/command/build_src.py", line 144, in run
        self.build_sources()
      File "/tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/command/build_src.py", line 155, in build_sources
        self.build_library_sources(*libname_info)
      File "/tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/command/build_src.py", line 288, in build_library_sources
        sources = self.generate_sources(sources, (lib_name, build_info))
      File "/tmp/pip-install-6n_fzlcg/numpy/numpy/distutils/command/build_src.py", line 378, in generate_sources
        source = func(extension, build_dir)
      File "numpy/core/setup.py", line 666, in get_mathlib_info
        raise RuntimeError("Broken toolchain: cannot link a simple C program")
    RuntimeError: Broken toolchain: cannot link a simple C program

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-6n_fzlcg/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-980d0neu/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-6n_fzlcg/numpy/
```
</p>
